# =============================================
# Configuración de la base de datos PostgreSQL
# =============================================
spring.datasource.url=jdbc:postgresql://localhost:5434/gfh_db
spring.datasource.username=postgres
spring.datasource.password=mimami
spring.datasource.driver-class-name=org.postgresql.Driver

# =============================================
# Configuración de JPA / Hibernate
# =============================================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# =============================================
# Configuración JWT
# Clave en Base64 de 64 bytes (512 bits) ? válida para HS256/HS512
# =============================================
app.jwt.secret=gfhRestauranteClaveSecreta2025AdminSeguridad
app.jwt.expiration-ms=86400000

# =============================================
# Configuración del servidor
# =============================================
server.port=8080
spring.application.name=GFH